export interface Trade {
  id: string;
  user_id?: string;
  market: string;
  market_category: 'Equities' | 'Crypto' | 'Forex' | 'Futures' | 'Other';
  symbol: string;
  type: 'Long' | 'Short';
  status: 'Open' | 'Closed';
  entry_price: number;
  exit_price?: number | null;
  quantity: number;
  entry_date: string;
  exit_date?: string | null;
  pnl?: number | null;
  pnl_percentage?: number | null;
  risk?: number | null;
  reward?: number | null;
  strategy?: string | null;
  tags?: string[] | null;
  notes?: string | null;
  leverage?: number | null;
  stop_loss?: number | null;
  take_profit?: number | null;
  commission?: number | null;
  fees?: number | null;
  slippage?: number | null;
  exchange?: string | null;
  timeframe?: string | null;
  setup_type?: string | null;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string | null;
} 